const { ethers } = require("hardhat");

async function main() {
  console.log("🚀 Deploying BuilderRewards contract to Mantle...\n");

  // Get the deployer account
  const [deployer] = await ethers.getSigners();
  console.log("📍 Deploying with account:", deployer.address);
  
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Account balance:", ethers.formatEther(balance), "MNT\n");

  // ============================================================
  // TOP 10 BUILDER ADDRESSES FROM YOUR LEADERBOARD
  // Generated by: node scripts/get-top-builders.js
  // ============================================================
  const initialBuilders = [
    "0x1b14891f4e6bd85656fb7f27c40fd1d66dd76d2b", // Rank 1: JulioMCruz.base.eth (score: 572)
    "0x3b7c4755e1a77c20ad287b8cdf04d97b967b074f", // Rank 2: Soko (score: 482)
    "0x8b7958d6365db1613dbaa76cc6b51ce086e7c9e8", // Rank 3: Sambit Sargam Ekalabya (score: 446)
    "0x1ea091521dc4a2035a586995f9fb7ca7b0f646ad", // Rank 4: Giovanni (score: 427)
    "0x65a9c8e981453e34c63bae9de5f6f36c070217b2", // Rank 5: Mohit bhat (score: 367)
    "0x5a1d61c71cfcf21f82129392d54f39e80139be30", // Rank 6: Akhil Nanavati (score: 355)
    "0x4f6a8245a9909aa97220581901f285a6f772026a", // Rank 7: ErikValle.eth (score: 348)
    "0x00e798f41616e19a2e7fd83cacd66d3ddd588101", // Rank 8: Cleaner (score: 346)
    "0xdf4de972fe0134a47eafe4bd114233681e06bd2b", // Rank 9: Yash Goyal (score: 324)
    "0x000ef5f21dc574226a06c76aae7060642a30eb74", // Rank 10: Luiz Vasconcelos (score: 322)
  ];

  console.log("📋 Top 10 Builders (by rank):");
  initialBuilders.forEach((addr, i) => {
    console.log(`   Rank ${i + 1}: ${addr}`);
  });
  console.log("");

  // Deploy the contract
  console.log("⏳ Deploying contract...");
  const BuilderRewards = await ethers.getContractFactory("BuilderRewards");
  const builderRewards = await BuilderRewards.deploy(initialBuilders);

  await builderRewards.waitForDeployment();
  const contractAddress = await builderRewards.getAddress();

  console.log("\n✅ BuilderRewards deployed successfully!");
  console.log("📍 Contract address:", contractAddress);
  console.log("\n🔗 View on Mantlescan:");
  console.log(`   https://mantlescan.xyz/address/${contractAddress}`);
  
  console.log("\n" + "=".repeat(60));
  console.log("📝 NEXT STEPS:");
  console.log("=".repeat(60));
  console.log("\n1. Update your .env.local file:");
  console.log(`   NEXT_PUBLIC_CONTRACT_ADDRESS=${contractAddress}`);
  console.log("\n2. Send ETH to the contract to fund rewards:");
  console.log(`   Contract address: ${contractAddress}`);
  console.log("\n3. Test distribution with a small amount (e.g., 0.00001 ETH)");
  console.log("\n4. When ready, click 'Distribute Rewards' on your website");
  console.log("=".repeat(60));
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
